#!/bin/bash
# setup.sh — One-command setup for network-triage-workflow
#
# Usage:
#   bash skills/network-triage-workflow/scripts/setup.sh
#
# What it does:
#   1. Checks for GITHUB_TOKEN
#   2. Clones ansible-network-triager (if not already present)
#   3. Installs the triager as a Python package
#   4. Creates a default config.yaml
#   5. Validates the setup with a dry run
#
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[OK]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
fail()  { echo -e "${RED}[FAIL]${NC} $1"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$SKILL_DIR/../../.." && pwd)"

# Default triager location: sibling to the content-networking-skills repo
TRIAGER_DIR="${TRIAGER_PATH:-$(cd "$REPO_ROOT/.." && pwd)/ansible-network-triager}"

echo ""
echo "=== network-triage-workflow setup ==="
echo ""

# --- Step 1: Check GITHUB_TOKEN ---
if [[ -z "${GITHUB_TOKEN:-}" ]]; then
    fail "GITHUB_TOKEN is not set."
    echo "  The triager needs a GitHub token to query repos."
    echo "  Create one at: https://github.com/settings/tokens"
    echo "  Scope needed: repo (read access to public repos)"
    echo ""
    echo "  Set it:"
    echo "    export GITHUB_TOKEN=\"ghp_your_token_here\""
    echo ""
    exit 1
fi
info "GITHUB_TOKEN is set"

# --- Step 2: Clone triager ---
if [[ -d "$TRIAGER_DIR" ]]; then
    info "Triager already exists at $TRIAGER_DIR"
else
    echo "Cloning ansible-network-triager to $TRIAGER_DIR ..."
    if git clone https://github.com/ansible-network/ansible-network-triager.git "$TRIAGER_DIR"; then
        info "Triager cloned"
    else
        fail "Could not clone triager. Check network and GitHub access."
        exit 1
    fi
fi

# --- Step 3: Install triager ---
echo "Installing triager as Python package..."
TRIAGER_INSTALLED=false

# Try editable install first (ideal — makes triager importable system-wide)
if (cd "$TRIAGER_DIR" && pip install -e . --quiet 2>/dev/null); then
    info "Triager installed (editable)"
    TRIAGER_INSTALLED=true
else
    # Try with --break-system-packages (needed on some distros)
    if (cd "$TRIAGER_DIR" && pip install -e . --quiet --break-system-packages 2>/dev/null); then
        info "Triager installed (editable, --break-system-packages)"
        TRIAGER_INSTALLED=true
    fi
fi

# Fallback: install just the dependencies (works in conda, venvs, etc.)
# The triager-json.py script adds the triager dir to sys.path directly,
# so we only need the deps — not a full pip install.
if [[ "$TRIAGER_INSTALLED" == "false" ]]; then
    warn "pip install -e . failed — installing dependencies only"
    DEPS="ptable requests PyYAML python-dotenv"
    if pip install $DEPS --quiet 2>/dev/null; then
        info "Dependencies installed ($DEPS)"
    elif pip install $DEPS --quiet --break-system-packages 2>/dev/null; then
        info "Dependencies installed ($DEPS, --break-system-packages)"
    else
        fail "Could not install dependencies. Check Python/pip setup."
        exit 1
    fi
    echo ""
    echo "  Note: triager-json.py will add the triager to sys.path at runtime."
    echo "  If you need 'triager' importable globally, fix pip install -e . manually."
fi

# --- Step 4: Create config.yaml if missing ---
TRIAGER_CONFIG="$TRIAGER_DIR/config.yaml"
if [[ -f "$TRIAGER_CONFIG" ]]; then
    info "config.yaml already exists at $TRIAGER_CONFIG"
else
    cat > "$TRIAGER_CONFIG" << 'EOF'
# ansible-network-triager configuration
# Generated by network-triage-workflow setup.sh
organization_name: "Ansible Networking"
workflow_name: "tests.yml"
timedelta: 14    # Look back N days for issues
EOF
    info "Created config.yaml at $TRIAGER_CONFIG"
fi

# --- Step 5: Set REPO_CONFIG if not set ---
if [[ -z "${REPO_CONFIG:-}" ]]; then
    warn "REPO_CONFIG env var is not set. Setting default network repos..."
    echo ""
    echo "  Add this to your shell profile (.bashrc, .zshrc):"
    echo ""
    cat << 'ENVEOF'
  export REPO_CONFIG='{
    "ansible-collections": {
      "ci_and_bug_repos": [
        "cisco.ios", "cisco.iosxr", "cisco.nxos",
        "arista.eos", "junipernetworks.junos", "cisco.asa",
        "ansible.netcommon", "ansible.utils"
      ],
      "bug_specific_repos": ["community.yang"]
    },
    "redhat-cop": {
      "ci_and_bug_repos": [
        "network.interfaces", "network.bgp", "network.base"
      ]
    }
  }'
ENVEOF
    echo ""
else
    info "REPO_CONFIG is set"
fi

# --- Step 6: Validate ---
echo ""
echo "Validating setup..."
if python -c "from triager.config import Config; print('triager importable')" 2>/dev/null; then
    info "Triager Python package is importable (globally)"
elif python -c "import sys; sys.path.insert(0, '$TRIAGER_DIR'); from triager.config import Config; print('triager importable via sys.path')" 2>/dev/null; then
    info "Triager importable via sys.path (triager-json.py handles this automatically)"
else
    warn "Triager not importable — check Python environment"
fi

echo ""
echo "=== Setup complete ==="
echo ""
echo "  Triager location:  $TRIAGER_DIR"
echo "  Config:            $TRIAGER_CONFIG"
echo "  Skill location:    $SKILL_DIR"
echo ""
echo "  Quick test:"
echo "    python $SKILL_DIR/scripts/triager-json.py --bugs --triager-path $TRIAGER_DIR"
echo ""
echo "  Or from Claude:"
echo "    triage network issues"
echo ""
